server:
  port: 8089
  servlet:
    context-path: /market/v1
    
    
spring:
  datasource:
    url: jdbc:h2:file:~/test
    driverClassName: org.h2.Driver
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate: 
        format_sql: true
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
      path: /h2-console

    
  